name: Daily Stock Data Update

on:
  schedule:
    - cron: '0 16 * * 1-5'  # 每周一到周五 UTC+0（北京时间 8 点）
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Sync dependencies with uv
        run: uv sync

      - name: Create and activate venv, run stock fetch
        run: |
          uv venv .venv
          source .venv/bin/activate
          python main.py --token=${{ secrets.TUSHARE_TOKEN }} --start=$(date +'%Y%m%d') --end=$(date +'%Y%m%d')

      - name: Install Hugging Face CLI
        run: |
          uv pip install huggingface_hub

      - name: Upload parquet to Hugging Face
        run: |
          for file in stock_data/daily/*.parquet; do
            huggingface-cli upload \
              --repo-type dataset \
              feilongfl/stock_tushare \
              "$file" \
              "data/$(basename $file)" \
              --token "$
