name: Daily Stock Data Update

on:
  schedule:
    - cron: '0 0 * * 1-5'  # 每周一到周五 UTC+1点（北京时间 9 点）
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: supplypike/setup-bin@v3
        with:
          uri: https://github.com/astral-sh/uv/releases/latest/download/uv-x86_64-unknown-linux-gnu.tar.gz
          name: uv
          bin-dir: /usr/local/bin

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Sync dependencies with uv
        run: uv sync

      - name: Run stock data fetch
        run: |
          uv venv .venv
          source .venv/bin/activate
          python main.py --token=${{ secrets.TUSHARE_TOKEN }} --start=$(date +'%Y%m%d') --end=$(date +'%Y%m%d')

      - name: Install Hugging Face CLI
        run: |
          uv pip install huggingface_hub

      - name: Upload parquet to Hugging Face
        run: |
          for file in stock_data/daily/*.parquet; do
            huggingface-cli upload \
              --repo-type dataset \
              feilongfl/stock_tushare \
              "$file" \
              "data/$(basename $file)" \
              --token "${{ secrets.HF_TOKEN }}" \
              --yes
          done
